name: Build and Deploy Hexo

on:
  push:
    branches:
      - sources

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          npm install

      - name: Build Hexo
        run: |
          npx hexo clean
          npx hexo generate

      - name: Deploy
        run: |
          cd public
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "deploy"
          git branch -M main
          git remote add origin https://losehu:${{ secrets.GH_TOKEN }}@github.com/losehu/DATASETS_PAGE.git
          git push -u origin main --force